name: vpe
description: "Video Player Extended"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.11.2
  window_manager: ^0.3.5
  provider: ^6.0.5
  file_picker: ^8.0.0+1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3 
  path_provider: ^2.1.5
  equatable: ^2.0.7

  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
